### PR TITLE
[minor] bump deps and fix vuln

### PR DESCRIPTION
**Pull request by tony-assembly**
fixes https://dev.azure.com/mx51/msp-be/_build/results?buildId=90327&view=logs&j=e9ed2dfc-30a0-5cbc-4218-5e108a7d7185&t=43b47557-ad5b-5b2f-e2c6-048dd0be5202&s=ebde4fd6-d75a-519f-682f-56c6fdb3cbb4

### CODE REVIEW

**Comment by tony-assembly** [comment]
@awilmore do we need to update any pipelines to ensure this is the version that is used during our builds?

**Review by PeterEFinch — APPROVED** [review]
Nice 👍 

I was just tracking down the sysdig vulnerability warning: https://app.us4.sysdig.com/secure/#/vulnerabilities/results/179367960cc33a03369bf5a39fd7ec80/vulnerabilities/179367960cc33a034acfd89754d63a92?filter=freeText+in+%28%22google.golang.org%2Fgrpc+v1.50.1%22%29

**Comment by tony-assembly** [comment]
> Nice 👍
> 
> I was just tracking down the sysdig vulnerability warning: https://app.us4.sysdig.com/secure/#/vulnerabilities/results/179367960cc33a03369bf5a39fd7ec80/vulnerabilities/179367960cc33a034acfd89754d63a92?filter=freeText+in+%28%22google.golang.org%2Fgrpc+v1.50.1%22%29

yeh this one was a head scratch, it came out of nowhere as part of an SLF PR which was having other issues so it threw a bit of a curveball 🤦

**Comment by PeterEFinch** [comment]
@tony-assembly I think we need to update [.default.env in msp-cicd-common](https://github.com/mx51/msp-cicd-common/blob/dc7781d6dbe5ec8910a535fae1e764d194b7bee3/.default.env#L15) as it use used to determine the probe version used in the [dockerfile](https://github.com/mx51/msp-cicd-common/blob/dc7781d6dbe5ec8910a535fae1e764d194b7bee3/docker/Dockerfile.common#L58-L61).

**Comment by tony-assembly** [comment]
> @tony-assembly I think we need to update [.default.env in msp-cicd-common](https://github.com/mx51/msp-cicd-common/blob/dc7781d6dbe5ec8910a535fae1e764d194b7bee3/.default.env#L15) as it use used to determine the probe version used in the [dockerfile](https://github.com/mx51/msp-cicd-common/blob/dc7781d6dbe5ec8910a535fae1e764d194b7bee3/docker/Dockerfile.common#L58-L61).

good spot!

**Comment by awilmore** [comment]
> @awilmore do we need to update any pipelines to ensure this is the version that is used during our builds?

Looks likes Peter found where that update needs to happen.

**Pull request merged**
